name: Flutter builds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.4
      - run: flutter pub get
      - run: flutter build apk
      
      - uses: actions/upload-artifact@v4
        with:
          name: healthapp-apk
          path: build/app/outputs/flutter-apk
